# Generated by Django 5.2.6 on 2025-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_info_source_remove_info_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
